# SPRING SETTINGS
spring:
  application:
    name: "kubernetes-demo-frontend"
  main:
    banner-mode: "off"
  output:
    ansi:
      enabled: always
  profiles:
    active: local

# ENDPOINTS
management:
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    git:
      mode: full

# SERVER
server:
  port: 8091
