apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-demo-frontend
  labels:
    app.kubernetes.io/name: kubernetes-demo-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernetes-demo-frontend
      app.kubernetes.io/name: kubernetes-demo-frontend
      app.kubernetes.io/instance: dev
  template:
    metadata:
      labels:
        app: kubernetes-demo-frontend
        app.kubernetes.io/name: kubernetes-demo-frontend
        app.kubernetes.io/instance: dev
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: kubernetes-demo-frontend
          image: "rahul21/kubernetes-demo-frontend:1.0-SNAPSHOT"
          imagePullPolicy: Always
          env:
            - name: JAVA_OPTS
              value: -Xmx256m
            - name: APP_INSTANCE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: BACKEND_ROUTE_URL
              value: "http://kubernetes-demo-backend/api/v1/backend/route"
          ports:
            - name: http
              containerPort: 8091
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8091
            initialDelaySeconds: 30
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8091
            initialDelaySeconds: 30
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi