apiVersion: v1
kind: Service
metadata:
  name:  kubernetes-demo-frontend
  labels:
    app.kubernetes.io/name: kubernetes-demo-frontend
    app.kubernetes.io/instance: dev
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: kubernetes-demo-frontend
    app.kubernetes.io/name: kubernetes-demo-frontend
    app.kubernetes.io/instance: dev