apiVersion: v1
kind: Service
metadata:
  name:  kubernetes-demo-backend
  labels:
    app.kubernetes.io/name: kubernetes-demo-backend
    app.kubernetes.io/instance: dev
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: kubernetes-demo-backend
    app.kubernetes.io/name: kubernetes-demo-backend
    app.kubernetes.io/instance: dev