apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-demo-backend
  labels:
    app.kubernetes.io/name: kubernetes-demo-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernetes-demo-backend
      app.kubernetes.io/name: kubernetes-demo-backend
      app.kubernetes.io/instance: dev
  template:
    metadata:
      labels:
        app: kubernetes-demo-backend
        app.kubernetes.io/name: kubernetes-demo-backend
        app.kubernetes.io/instance: dev
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: kubernetes-demo-backend
          image: "rahul21/kubernetes-demo-backend:1.0-SNAPSHOT"
          imagePullPolicy: Always
          env:
            - name: JAVA_OPTS
              value: -Xmx256m
            - name: APP_INSTANCE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - name: http
              containerPort: 8092
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8092
            initialDelaySeconds: 30
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8092
            initialDelaySeconds: 30
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi